### ISSUE TITLE
Make it work on Firefox

### ISSUE THREAD

**Issue by LostInBrittany** [warp-poke/poke-ui#16]
Current version doesn't :(

**Comment by LostInBrittany** [comment]
The underlying bug seems to be a Stencil bug, so waiting for their return on https://github.com/ionic-team/stencil/issues/1047 before going further.

**Comment by urcadox** [comment]
What didn't work?

**Comment by LostInBrittany** [comment]
this one could be closed now...

**Comment by urcadox** [comment]
That's what I figured, I have no issues (other than the one I opened earlier). Closing this.
